### ISSUE TITLE
Determine the version of Unity we will use as our base

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#11]
We will not take any LTS version beyond 1.1.2024 for terms of service security ( see [here](https://unity.com/pricing-updates) ) 
Once the project is ready to be started, our first task is updating Unity to the current stable version and then ensuring that all package updates works fine. 

Future Unity updates will require full testing so we will discuss any unity upgrade possibilities as a team as they occur.

**Comment by baconeta** [comment]
Current version as of now is 2022.3.20f1 https://unity.com/releases/editor/whats-new/2022.3.20

**Comment by SabrinaTheCookie** [comment]
2022.3.20f1 is acceptable - let's try not to change versions 💀 
 
 I've upgraded the project to the latest version
