### ISSUE TITLE
Add all (currently planned) analytics to the Unity Dashboard

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#120]
https://docs.google.com/spreadsheets/d/1LiQ1mQXyczKOnPEM57qDJWwtB2rO6SGXNI04l-rh9j8/edit?gid=0#gid=0

Every custom event should have all its own events as well as the default analytics that are sent with every event
There might be a specific way to optimise this for Unity Analytics but I think we don't worry about that too much

Here is the direct link to unity analytic events
https://cloud.unity.com/home/organizations/5772564645095/projects/cd385f04-145d-4ec1-b1c0-15da9b1e2feb/environments/1baa82bb-6f78-4883-b817-b0aeb8f8f5b2/analytics/v2/events

**Comment by JamesCoburn246** [comment]
1. Added parameters for `DEFAULT ANALYTICS` to the dashboard.
2. Added events `LevelStartedEvent` and `StagePlacementEvent` (as well as their associated parameters) to the dashboard.

**Comment by JamesCoburn246** [comment]
Added events `LevelCompletedEvent`, `LevelAbandonEvent`, `LogErrorEvent` (as well as their associated parameters) to the dashboard.

This concludes the last of the dashboard content to be added (at the time of writing this comment).
