### ISSUE TITLE
Create a vertical-slice branch from the main game to use for dev

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#20]
Part of #17 

This will give us 

-------main-----
|
\\----------- vertical-slice
              \\
              ---------------feature branches
              
 Git tree flow

**Comment by SabrinaTheCookie** [comment]
Do we need _vertical slice_? We could just use _main_, or are you intending _vertical-slice_ to merge into _main_  semi-regularly with stable versions? Seems like extra steps we may not need.

**Comment by baconeta** [comment]
I was anticipating building from their but allowing other features to be expanded or built that won't be polished for the vertical slice. How much extra work do you think this might be? Seems minimal to me

**Comment by SabrinaTheCookie** [comment]
yup seems minimal, i'll do this ticket now.
