### ISSUE TITLE
Create first instrument for integrating with characters

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#29]
Obviously this requires some of the elements of  the music to be completed so relies on #23 #22

**Comment by baconeta** [comment]
I'd say that we can close this task - what do you think @kusahlstedt ?
I think your guitar you did will help us a lot - or are you still actually going to work on it more?

**Comment by kusahlstedt** [comment]
i think i’ll add some simple shading and highlights and export it as a pfd
file, though it’s practically already done so that can be closed👍

**Comment by baconeta** [comment]
Sweet. Once you export the file, jsut pop here and close the issue at the bottom :)
