### ISSUE TITLE
Create and flesh engineering for core game experience

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#31]

**Comment by SabrinaTheCookie** [comment]
This is a pretty big undertaking that is going to rely heavily on #38 too. But ultimately we need the following:

- Audio System
- - Dynamic Loading
- Input System
- - Tap, Drag+Drop, Zoom, 
- Act System
- - Keeps track of what chapters are a part of the act and which are done
- - Loads in chapters dynamically as additive scenes as needed. No loading screens!
- - Initiates all of the cutscenes.
- Chapter System
- - Actual game flow
- Save System
- - We need to think of a solution for this.

**Comment by baconeta** [comment]
I'll get you a draft idea of how I think the core experience will look and feel asap. Maybe tonight. Then you can think about how the engineering might need to flex for that or some of the design could need to be changed. 

I'll comment on the save system stuff separately later

**Comment by baconeta** [comment]
We have a lot of this coming together now which is nice

New addition - stage/env scrollability

Unsure about tooltips because of the new carousel view idea we had so maybe we can come back to that.

**Comment by baconeta** [comment]
Completing #16 and #81 will close this issue
