### ISSUE TITLE
Create a reasonable menu -> flow into the vertical slice version of the game

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#40]
Not much to say here - it doesn't have to be the final game flow and we could have a special flow for the slice if we want to

**Comment by SabrinaTheCookie** [comment]
This has been started. Main Menu -> Play -> Act <-> Chapter(s)
Super duper basic opening/closing of chapters with a return to menu button.
No graphics added.

**Comment by baconeta** [comment]
Let's leave this in progress until we have a core loop and make sure a slice version with this flow feels just right (I'm sure it will but just in case)

**Comment by baconeta** [comment]
Closing for now, if we want to add Act selection we will make a new ticket
