### ISSUE TITLE
[26-06-24]Submit for Kiwi Game Starter

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#42]
https://www.kiwigamestarter.com/2024comp/

![image](https://github.com/Baconeta-Studios/setting-the-stage/assets/87751532/375a53d6-5ba7-4d6d-9d84-e6d3dddb27e9)

**Comment by SabrinaTheCookie** [comment]
@baconeta Wanting to confirm this ticket is Kiwijam, and you're not meaning [Kiwi Game Starter](https://www.kiwigamestarter.com/2024comp/)?

**Comment by baconeta** [comment]
That is correct, you can correct the ticket for me 😅
