### ISSUE TITLE
Save System Implementation

### ISSUE THREAD

**Issue by SabrinaTheCookie** [Baconeta-Studios/setting-the-stage#45]
How are we implementing this?

**Comment by baconeta** [comment]
What do you think about this?

https://stackoverflow.com/questions/63082956/what-is-best-practice-to-save-game-progress-in-a-game-made-in-unity3d-along-diff

**Comment by baconeta** [comment]
One possible implementation https://stackoverflow.com/questions/59469999/why-doesnt-my-save-system-work-on-android

**Comment by SabrinaTheCookie** [comment]
> What do you think about this?
> 
> https://stackoverflow.com/questions/63082956/what-is-best-practice-to-save-game-progress-in-a-game-made-in-unity3d-along-diff

I think this is the best solution. Lets go with this :)
