### ISSUE TITLE
Game flow flowchat

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#6]
We should plan a rough flowchart indicating how we might want the game flow to behave from start to finish

This doesn't need to be fixed but it should indicate roughly what important elements we would require on certain screens to give the designer a jumping off point to create mockups for #7 

This can be done independantly of style but some progress there may support this in terms of self visualisation and mental mind mapping

**Comment by baconeta** [comment]
https://www.canva.com/design/DAF9sQKQbSQ/JyG9LW4kVxJajsbSULE_8g/edit Pending some other people to check and say they are or are not happy with it

Preferably @amruthvarshan and @SabrinaTheCookie

**Comment by SabrinaTheCookie** [comment]
I've added a slight variation below the current existing flowchart. I've added notes too.

**Comment by baconeta** [comment]
Considering overall game architecture do you sre any issues with either approach? @SabrinaTheCookie

**Comment by SabrinaTheCookie** [comment]
Honestly no issues with either approach - Version 2 is slightly simplified with rolling the Tutorial into Chapter/Act 1.

**Comment by baconeta** [comment]
I think that merging a tutorial into the game is good as long as it plays to be fun and skipping it is not a disadvantage to the flow/progress we create (whether it be total star system which is the current plan, or not).

**Comment by baconeta** [comment]
Update btw, I think the v2 is the approach to go with. I like it and can't see any real issues with it actually.
