### ISSUE TITLE
Add prerequisite that previous chapter must be completed and passed before unlocking next 

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#66]
We will discuss whether we allow all plays to count as a play or if there will be a failure flow separately to make it clear that we don't unlock the next song. There should be some minimum requirement for unlocking the next chapter and it should be overrideable by chapter but have a default global value too.

**Comment by SabrinaTheCookie** [comment]
Decided that Acts have no entry prerequisite, chapters have no entry pre-requisite. Acts completion requires that all chapters are completed, and have a minimum number of stars. e.g. you need 6/9 stars in the act to complete it.
