### ISSUE TITLE
Add puzzle elements for UI in game (characters + instruments if needed) [Programming]

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#74]
Created from task #38 

This focuses on the Puzzle aspect - work out how to position things on the screen and how we might display information to the player about the track puzzle 

Requires the mockup at least from #71

If done after all assets are given already then this would also close the implementation ticket #73

**Comment by baconeta** [comment]
Note (will be more clear once Mockup is added here)

MAIN GAME STAGE SCREEN
-> Selecting a spot opens the selection UI - dims the main stage except for a spotlight on the selected spot
-> Camera straightens up and zooms into that spot
-> Background can no longer be interacted with until the UI is closed (there will be a button or something like that - or simply clicking in the background could be an option we consider)
-> There will be arrows to the edge of screen to allow a player to change which stage spot is highlighted - camera moves accordingly but is only automatic


This above might prevent weird camera bugs from occurring during selection time

**Comment by SabrinaTheCookie** [comment]
progressed by #83
