### ISSUE TITLE
Figure out what settings we want on the game settings menu

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#87]
Just making a list of the settings we want to give the user the choice to change in game from the widget settings menu

We definitely want: 
- Volume controls
- Quit chapter

anything else?

**Comment by JamesCoburn246** [comment]
Should analytics opt-in/opt-out toggle be in here? Up for you two to decide ultimately

**Comment by baconeta** [comment]
> Should analytics opt-in/opt-out toggle be in here? Up for you two to decide ultimately

A good idea actually. Let's see if we mimic the same settings in the main menu settings as here. If we do- then yet
Otherwise I think it reduces bugs to keep that out of the in game flow

**Comment by baconeta** [comment]
Hint/help maybe - to assess later but now we close
