### ISSUE TITLE
Finalise stage asset

### ISSUE THREAD

**Issue by baconeta** [Baconeta-Studios/setting-the-stage#94]
All we need to do is simply expand the same canvas a small amount above the top of the wider stage asset and add a completed top piece so that sits on the 3d models we work with without looking out of place. 

Finetuning/polishing the stage asset can come later so long as the canvas size and positioning remains the same

**Comment by baconeta** [comment]
Base version of this is now done I believe
@kusahlstedt can you add this to the drive? Happy for you to keep polishing it just let us know whenever you do so we can override the version in the game :D

**Comment by kusahlstedt** [comment]
fine if i add the widest version of sthe stage without the clutter and an unfinished door? won’t be the final version but the size of it would be
